### ISSUE TITLE
Publish would bundle old version

### ISSUE THREAD

**Issue by jeschkies** [yananhub/flying-gradle-plugin#5]
Thanks for this plugin. I was struggling quite a bit to get a release out.

I've found an issue. When I release one version and then increased the version number and would release another version the second bundle would include the files from the first bundle. I had to remove the files from `repos/bundles` first.

**Comment by yananhub** [comment]
@jeschkies

As a workaround, you can avoid the issue by running **clean** before publishing tasks. Like this:
```shell
$ ./gradlew clean publish publishToMavenCentralPortal
```
Of course, I will try to solve this issue in a later version.

**Comment by jeschkies** [comment]
Thanks. That should be fine for a release from the CI :slightly_smiling_face:
